config/routes.rb
Smartdrum::Application.routes.draw do

  get "profiles/show"

  get "profiles/new"

  get "profiles/delete"

  get "profiles/edit"

  get "profiles/update"

  get "profiles/create"

  get "profile/show"

  get "profile/new"

  get "profile/delete"

  get "profile/edit"

  get "profile/update"

  get "profile/create"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "pages/home"

  get "pages/partners"

  get "pages/contacts"

  get "pages/employers"

  get "pages/about"

  get 'tags/:tag', to: 'records#index', as: :tag

  match 'about' => 'pages#about'
  match 'employers' => 'pages#employers'
  match 'contacts' => 'pages#contacts'
  match 'partners' => 'pages#partners'
  match 'home' => 'pages#home'

  resources :products, :only => [:index, :show]
  resources :news, :only => [:index, :show]
  resources :records, :only => [:index, :show]
  resources :profiles, :only => [:show, :edit, :new, :create, :update]
  resources :news_comments, :only => [:create, :destroy]
  resources :prod_comments, :only => [:create, :destroy]
  resources :record_comments, :only => [:create, :destroy]

  root :to => 'pages#home'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :registrations => "registrations" }
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :comments_blog, :dependent => :destroy
  attr_accessible :data, :header
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  attr_accessible :text
end

app/models/comments_blog.rb
class CommentsBlog < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  attr_accessible :data
end

app/models/comments_news.rb
class CommentsNews < ActiveRecord::Base
  belongs_to :user
  belongs_to :news
  attr_accessible :data
end

app/models/comments_prod.rb
class CommentsProd < ActiveRecord::Base
  belongs_to :user
  belongs_to :production
  attr_accessible :data
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  attr_accessible :department, :firstname, :lastname
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :header, :text
  validates :header, :length => {:in => 4..255}, :presence => true
  has_many :news_comment, :dependent => :destroy

  searchable do
    text :header, :text
  end
end

app/models/news_comment.rb
class NewsComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :news
  attr_accessible :text, :user_id, :news_id
  validates :text, :presence => :true
  searchable do
    text :text
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :name, :title
  validates :content, :name, :title, :presence => true
end

app/models/prod_comment.rb
class ProdComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  attr_accessible :text, :user_id, :product_id
  validates :text, :presence => :true

  searchable do
    text :text
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :count, :description, :image, :name, :price
  mount_uploader :image, ImageUploader
  has_many :prod_comment, :dependent => :destroy
  validates :name, :uniqueness => true, :presence => true

  searchable do
    text :name, :description
  end
end

app/models/production.rb
class Production < ActiveRecord::Base
  attr_accessible :cost, :count, :description, :name
  has_many :comments_prod, :dependent => :destroy
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :about, :firstname, :image, :lastname, :user_id
  mount_uploader :image, ImageUploader
  validate :firstname, :lastname, :presence => true
end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :header, :text, :tag_list
  acts_as_taggable
  has_many :record_comment, :dependent => :destroy
  validates :header, :length => {:in => 4..255}, :presence => true
  validates :text, :presence => true

  searchable do
    text :text, :tag_list
  end
end

app/models/record_comment.rb
class RecordComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :record
  attr_accessible :text, :user_id, :record_id
  validates :text, :presence => :true

  searchable do
    text :text
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_one :profile, :dependent => :destroy
  has_many :news_comment, :dependent => :destroy
  has_many :prod_comment, :dependent => :destroy
  has_many :record_comment, :dependent => :destroy
end

app/controllers/records_controller.rb
#encoding : utf-8
class RecordsController < ApplicationController
  def index
    @title = 'Блог'
    if params[:tag]
      @blog = Record.tagged_with(params[:tag]).page(params[:page]).per(5)
    else
      @blog = Record.order("created_at DESC").page(params[:page]).per(5)
    end
  end

  def show
    @record = Record.find(params[:id])
    @title = @record.header
    @comments = @record.record_comment.page(params[:page]).per(10)
    if user_signed_in?
      @comment = RecordComment.new
      @comment.record_id = @record.id
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/records/index.html.haml
%h2 Наш блог
- unless @blog.nil?
  .container
  %h3{:style => 'text-align : left'} Теги : 
  #tag_cloud
    %ul.breadcrumb
      - tag_cloud Record.tag_counts, %w[s m l] do |tag, css_class|
        %li= link_to tag.name, tag_path(tag.name), class: css_class
    - @blog.each do |record|
      .row
        %hr
        %a{:href => record_path(record.id)} 
          %h2= record.header
        .span2
          %p{:style => 'font-weight : bold'} Добавлено:
          %p=record.created_at.to_s(:ru_datetime)
        .span8
          = render :inline => record.text
        .span2
          %p{:style => 'font-weight : bold'} Обновлено:
          %p{:style => ''}=record.created_at.to_s(:ru_datetime)
      .row{:style => 'margin-top : 16px; text-align : center'}
        .span2
        .span8
          - unless record.tag_list.empty?
            %p{:style => 'font-weight : bold'} Теги:
            - record.tag_list.each do |tag|
              = link_to(tag, '/tags/' + tag)
        .span2
    = paginate @blog

app/views/records/show.html.haml
- unless @record.nil?
  .container
    .row
      %hr
      %h2= @record.header
      .span2
        %p{:style => 'font-weight : bold'} Добавлено:
        %p=@record.created_at.to_s(:ru_datetime)
      .span8
        = render :inline => @record.text
      .span2
        %p{:style => 'font-weight : bold'} Обновлено:
        %p{:style => ''}=@record.created_at.to_s(:ru_datetime) 
    .row{:style => 'margin-top : 16px; text-align : center'}
      .span2
      .span8
        - unless @record.tag_list.empty?
          %p{:style => 'font-weight : bold'} Теги:
          %ul.breadcrumb
            - @record.tag_list.each do |tag|
              %li= link_to(tag, '/tags/' + tag) 
      .span2
    = render 'layouts/socialbuttons'
    = render :partial => 'layouts/addcomments', :locals => {:control => 'record_comments', :id => 'record_id'.intern}
    = render 'layouts/comments'