config/routes.rb
Smartdrum::Application.routes.draw do

  get "profiles/show"

  get "profiles/new"

  get "profiles/delete"

  get "profiles/edit"

  get "profiles/update"

  get "profiles/create"

  get "profile/show"

  get "profile/new"

  get "profile/delete"

  get "profile/edit"

  get "profile/update"

  get "profile/create"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "pages/home"

  get "pages/partners"

  get "pages/contacts"

  get "pages/employers"

  get "pages/about"

  get 'tags/:tag', to: 'records#index', as: :tag

  match 'about' => 'pages#about'
  match 'employers' => 'pages#employers'
  match 'contacts' => 'pages#contacts'
  match 'partners' => 'pages#partners'
  match 'home' => 'pages#home'

  resources :products, :only => [:index, :show]
  resources :news, :only => [:index, :show]
  resources :records, :only => [:index, :show]
  resources :profiles, :only => [:show, :edit, :new, :create, :update]
  resources :news_comments, :only => [:create, :destroy]
  resources :prod_comments, :only => [:create, :destroy]
  resources :record_comments, :only => [:create, :destroy]

  root :to => 'pages#home'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :registrations => "registrations" }
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :comments_blog, :dependent => :destroy
  attr_accessible :data, :header
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  attr_accessible :text
end

app/models/comments_blog.rb
class CommentsBlog < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  attr_accessible :data
end

app/models/comments_news.rb
class CommentsNews < ActiveRecord::Base
  belongs_to :user
  belongs_to :news
  attr_accessible :data
end

app/models/comments_prod.rb
class CommentsProd < ActiveRecord::Base
  belongs_to :user
  belongs_to :production
  attr_accessible :data
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  attr_accessible :department, :firstname, :lastname
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :header, :text
  validates :header, :length => {:in => 4..255}, :presence => true
  has_many :news_comment, :dependent => :destroy

  searchable do
    text :header, :text
  end
end

app/models/news_comment.rb
class NewsComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :news
  attr_accessible :text, :user_id, :news_id
  validates :text, :presence => :true
  searchable do
    text :text
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :name, :title
  validates :content, :name, :title, :presence => true
end

app/models/prod_comment.rb
class ProdComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  attr_accessible :text, :user_id, :product_id
  validates :text, :presence => :true

  searchable do
    text :text
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :count, :description, :image, :name, :price
  mount_uploader :image, ImageUploader
  has_many :prod_comment, :dependent => :destroy
  validates :name, :uniqueness => true, :presence => true

  searchable do
    text :name, :description
  end
end

app/models/production.rb
class Production < ActiveRecord::Base
  attr_accessible :cost, :count, :description, :name
  has_many :comments_prod, :dependent => :destroy
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :about, :firstname, :image, :lastname, :user_id
  mount_uploader :image, ImageUploader
  validate :firstname, :lastname, :presence => true
end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :header, :text, :tag_list
  acts_as_taggable
  has_many :record_comment, :dependent => :destroy
  validates :header, :length => {:in => 4..255}, :presence => true
  validates :text, :presence => true

  searchable do
    text :text, :tag_list
  end
end

app/models/record_comment.rb
class RecordComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :record
  attr_accessible :text, :user_id, :record_id
  validates :text, :presence => :true

  searchable do
    text :text
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_one :profile, :dependent => :destroy
  has_many :news_comment, :dependent => :destroy
  has_many :prod_comment, :dependent => :destroy
  has_many :record_comment, :dependent => :destroy
end

app/controllers/news_controller.rb
#encoding: utf-8
class NewsController < ApplicationController
  def index
    @title = 'Новости'
    @news = News.order("created_at DESC").page(params[:page]).per(5)
    @newsrss = News.order("created_at DESC").limit(20)

    respond_to do |format|
      format.html
      format.atom { render :layout => false }
    end
  end

  def show
    @news = News.find(params[:id])
    @title = @news.header
    @comments = @news.news_comment.page(params[:page]).per(10)
    if user_signed_in?
      @comment = NewsComment.new
      @comment.news_id = @news.id
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
#encoding : utf-8
module ProfileHelper
   def deny_access
    redirect_to root_path, :notice => "Вы должны быть зарегистрированы."
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/news/edit.html.haml
- if current_user.admin?
  %h2 Изменить новость
  =form_for(@news) do |news|
    .field
      = news.label "Заголовок новости :"
      = news.text_field :header
    .field
      = news.label "Содержание :"
      %br
      = news.text_area :data, :class => "tinymce", :rows => 10, :cols => 60
    .actions
      = news.submit "Изменить"

app/views/news/index.html.haml
%h2 Наши новости
- unless @news.nil?
  - content_for :head, auto_discovery_link_tag(:atom, news_index_path(format: "atom"))
  %a{:href => news_index_path(format: "atom")} 
    %i.icon-rss.large 
    %p Подписаться на RSS
  .container
    - @news.each do |newz|
      .row
        %hr 
        %a{:href => news_path(newz.id)} 
          %h2= newz.header
        .span2
          %p{:style => 'font-weight : bold'} Добавлено:
          %p=newz.created_at.to_s(:ru_datetime)
        .span8
          = render :inline => newz.text if newz.text
        .span2
          %p{:style => 'font-weight : bold'} Обновлено:
          %p{:style => ''}=newz.created_at.to_s(:ru_datetime)
    = paginate @news

app/views/news/new.html.haml
- if current_user.admin?
  %h2 Добавление новости
  =form_for(@news) do |news|
    .field
      = news.label "Заголовок новости :"
      = news.text_field :header
    .field
      = news.label "Содержание :"
      = news.text_area :data, :class => "tinymce", :rows => 10, :cols => 60
    .actions
      = news.submit "Добавить"

app/views/news/show.html.haml
- unless @news.nil?
  .container
    .row
      %hr
      %h2= @news.header
      .span2
        %p{:style => 'font-weight : bold'} Добавлено:
        %p=@news.created_at.to_s(:ru_datetime)
      .span8
        = render :inline => @news.text if @news.text
      .span2
        %p{:style => 'font-weight : bold'} Обновлено:
        %p{:style => ''}=@news.created_at.to_s(:ru_datetime)
    = render 'layouts/socialbuttons'
    = render :partial => 'layouts/addcomments', :locals => {:control => 'news_comments', :id => 'news_id'.intern}
    = render 'layouts/comments'